myapp/hello/urls.py
from django.urls import path

from . import views 

app_name= 'hello'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('hello/', include('hello.urls')),
    path('admin/', admin.site.urls),
]

myapp/hello/models.py
import datetime
from django.db import models

# Create your models here.
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

myapp/hello/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'hello/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'hello/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'hello/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'hello/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('hello:results', args=(question.id,)))

myapp/hello/templates/hello/detail.html
<html>
<head>

<title>
</title>

</head>

<body>       
	{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">

{{ question }}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'hello:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

</body>
</html>

myapp/hello/templates/hello/index.html
<html>
  <head>


     <title>

     </title>

  </head>
  <body>
      {% include 'material/includes/material_css.html' %}
      {% include 'material/includes/material_js.html' %}

       {% load material_form %}

     {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hello/style.css' %}">

<marquee scroll:left>VOTING TIME................... PLEASE VOTE</marquee>

  <div class= "Abc">

     {% if latest_question_list %}
      <ul>
          {% for question in latest_question_list %}
        <li><a href="{% url 'hello:detail' question.id %}">{{ question.question_text }}</a></li>

          {% endfor %}
      </ul>
     {% else %}
         <p>No polls are available.</p>
     {% endif %}
</div>

</body>
</html>

myapp/hello/templates/hello/results.html
<html>
<head>
<title>
</title>

</head>
<body>
	{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hello/style.css' %}">

     <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'hello:detail' question.id %}">Vote again?</a>

</body>
</html>